### ISSUE TITLE
How to support chinese?

### ISSUE THREAD

**Issue by GeorgeXiaojie** [tshu-w/DBCopilot#5]
Thanks for sharing and also read your paper, great work. May I ask, if I want to support Chinese, how to realize it? The database table comments are in Chinese, and the user's questions are also in Chinese.

Looking forward to your reply

**Comment by GeorgeXiaojie** [comment]
That's a great idea, and I will try it as you suggested. Thank you very much.

**Comment by tshu-w** [comment]
If you have more questions, feel free to continue contacting us.
