### ISSUE TITLE
数据集链接打不开

### ISSUE THREAD

**Issue by Tonyk8** [tshu-w/DBCopilot#6]
作者你好，请问可以提供获取数据集的方式吗，链接已经无法访问

**Comment by tshu-w** [comment]
<img width="1057" alt="Screenshot 2024-11-11 at 19 23 28" src="https://github.com/user-attachments/assets/d20842c3-cc30-4583-8ea7-92910455c648">
刚刚隐私模式试了一下没问题，可能需要些众所周知的手段？

**Comment by Tonyk8** [comment]
已经科学上网，
![1](https://github.com/user-attachments/assets/823f6f90-3597-40c1-890c-f7d5bb769e8e)
我这边显示是这样的

**Comment by Tonyk8** [comment]
> 试试看直接访问 https://onedrive.live.com 是否可以（代理软件全局模式）？

已经可以成功访问了，非常感谢
